export const elements = {
    tetris_main_Grid: document.querySelector(".tetris__Container") as HTMLDivElement,
    tetris_preview_Grid: document.querySelector(".right__Container__upcoming__tetris--grid") as HTMLDivElement,
    tetris_Score: document.querySelector(".info__score") as HTMLDivElement,
    tetris_Level: document.querySelector(".info__level") as HTMLDivElement,
    tetris_Lines: document.querySelector(".info__lines") as HTMLDivElement,
    tetris_start: document.querySelector(".btn__start") as HTMLButtonElement,
    tetris_pause: document.querySelector(".btn__pause") as HTMLButtonElement,
    tetris_resume: document.querySelector(".btn__resume") as HTMLButtonElement,
    tetris_quit: document.querySelector(".btn__quit") as HTMLButtonElement,
    tetris_preview_blocks: document.querySelectorAll(".right__Container__upcoming__tetris--grid div") as NodeListOf<HTMLElement>,
    tetris_main_blocks: document.querySelectorAll(".tetris__Container div") as NodeListOf<HTMLElement>,
    tetris_song: document.getElementById("tetris__music") as HTMLAudioElement,
    tetris_intro: document.getElementById("tetris__intro") as HTMLAudioElement,
    tetris_level_up: document.getElementById("tetris__level__up") as HTMLAudioElement,
    tetris_single_row_audio: document.getElementById("tetris__single__row") as HTMLAudioElement,
    tetris_double_row_audio: document.getElementById("tetris__double__row") as HTMLAudioElement,
    tetris_triple_row_audio: document.getElementById("tetris__triple__row") as HTMLAudioElement,
    tetris_tetris_row_audio: document.getElementById("tetris__tetris__row") as HTMLAudioElement,
    tetris_landing_audio: document.getElementById("tetris__landing") as HTMLAudioElement,
    tetris_move_audio: document.getElementById("tetris__move") as HTMLAudioElement,
    tetris_rotate_audio: document.getElementById("tetris__rorate") as HTMLAudioElement,
    tetris_pause_audio: document.getElementById("tetris__pause") as HTMLAudioElement,
    tetris_gameover_audio: document.getElementById("tetris__gameover__audio") as HTMLAudioElement,
    tetris_noice_audio: document.getElementById("tetris__noice") as HTMLAudioElement,
    tetris_impressive_audio: document.getElementById("tetris__impressive") as HTMLAudioElement,
    tetris_excellence_audio: document.getElementById("tetris__excellence") as HTMLAudioElement,
    tetris_gameover: document.querySelector(".gameover__container") as HTMLDivElement,
    tetris_play_again: document.querySelector(".gameover__btn") as HTMLButtonElement
}